### ISSUE TITLE
Support referencing another recipe / linking

### ISSUE THREAD

**Issue by bbstilson** [cooklang/spec#16]
For example, consider a simple recipe for baked salmon, and then a meal recipe that says to use that recipe, then do other things for sides. It would be nice to be able to do something like:

```
Prepare the salmon according to [this recipe](/Simple Salmon Bake.cook).

Bake the @potatoes{2} for ~{30%minutes}.
```

**Comment by dubadub** [comment]
Let's move discussion about this to https://github.com/cooklang/spec/issues/10

**Comment by dubadub** [comment]
Closing as duplicate
