### ISSUE TITLE
Terminate ingredient and cookware with same symbol

### ISSUE THREAD

**Issue by Scoder12** [cooklang/spec#17]
Just throwing this out there, but maybe being able to write something like `@ground pepper@` or `#potato masher#` would look a little nicer and save 1 character. 
It's symmetrical and avoiding braces is nice. 

When specifying quantity, brackets would still be used, e.g. `@ground pepper@` and `@ground pepper{}` are both valid and equivalent, but you would still write `@potato{2kg}`.

Only drawback is that it creates 2 ways to do one thing. Perhaps empty brackets (`{}`) could be made illegal so as to ensure there is only ever 1 valid format.

**Comment by luizribeiro** [comment]
I feel like this would create unnecessary ambiguity on the language and it would over-complicate some of the regular expressions that can be used for doing matching.

For example, if you have a line that looks like:

```cook
Add @black pepper@ and @salt@
```

If you have a typo and you accidentally leave the `@` with a space before and next to `and`:

```cook
Add @black pepper @and @salt@
```

It isn't clear to the parser if you meant "Add **black pepper** and **salt**" or "Add **black** pepper **and** **salt**"

Not sure if we should be optimizing for such mistakes, but I personally like the current syntax as it encourages me to include quantities.

**Comment by Scoder12** [comment]
Makes sense
