### ISSUE TITLE
Clarify cookware quantity

### ISSUE THREAD

**Issue by Scoder12** [cooklang/spec#18]
Can/should cookware be able to have a quantity, e.g. `#pot{2}`?

**Comment by dubadub** [comment]
It should. Used not often but in some cases it can be helpful. For example, when cooking muffins one may use cups like these.

![71fIYKVRo7L _AC_SL1500_](https://user-images.githubusercontent.com/4168619/140713153-6544f35b-9765-4894-b27d-d23a9ec12a94.jpg) ([source](https://www.amazon.co.uk/Silicone-Reusable-Cupcake-Non-Stick-Bakeware/dp/B08RBQ9K7V/ref=asc_df_B08RBQ9K7V/?tag=googshopuk-21&linkCode=df0&hvadid=500867631722&hvpos=&hvnetw=g&hvrand=1943345288156295388&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1007850&hvtargid=pla-1186636185076&psc=1)).

**Comment by dubadub** [comment]
@Scoder12 is that okay to close the issue? I described what to expect from cookware in more details https://github.com/cooklang/spec/blob/main/EBNF.md?plain=1#L16.

**Comment by Scoder12** [comment]
Sure, thanks.
