### ISSUE TITLE
Provide a BNF of the language spec or a canonical test suite

### ISSUE THREAD

**Issue by heytherewill** [cooklang/spec#27]
I'm working on an implementation of CookLang for .NET (found [here](https://github.com/heytherewill/cooklangnet)). It currently covers most scenarios, but the lack of a canonical description of what is valid in CookLang makes covering edge cases hard.

For example, there's no specification of what characters are valid for words, thus making it hard to unit test for languages that don't use ASCII.

What I'm requesting here is to either have a BNF specification of CookLang or a suite of tests containing several recipes that stress the language to its limits along with the expected output of each recipe. This will make the implementations of CookLang much more solid.

**Comment by umgefahren** [comment]
I think a abstract language description would be pretty necessary. I faced the same issues with my [Rust implementation](https://github.com/umgefahren/cook-with-rust). Edge cases are a problem and the language is insufficient defined.

However I would be prefer EBNF over BNF, because it's more readable.

Resources:
 - [EBNF Wikipedia](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form)

**Comment by dubadub** [comment]
Great idea! For me being amateur it's fun to figure it out. I started the document here https://github.com/cooklang/spec/blob/main/EBNF.md. I think we should both EBNF spec and tests.

**Comment by dubadub** [comment]
@heytherewill @umgefahren I finalised current language description in https://github.com/cooklang/spec/blob/main/EBNF.md. Is that what you expected? Or I should change something?

**Comment by heytherewill** [comment]
Thanks, @dubadub , that looks brilliant and absolutely helps with implementing things properly!

A few things I noticed that are part of the EBNF but not mentioned in the readme:

- Cookware quantity is valid (is this correct or a mistake? I think it should be valid)
- Timers can have names
- Ingredients, timers and equipment can only use the latin alphabet whereas comments, steps and metadata can use whatever (I think the spec for the special elements is too restraining. Even if we are not talking about non-latin alphabet languages, diacritics are not included as valid alphabetic characters)

Also, it should be really important to be explicit that the EBNF should be the final source of truth; that is, if the docs say something and the EBNF say something else, the EBNF is what implementations should follow.

Other than these details, the spec looks great and is exactly what I had in mind, cheers!

**Comment by dubadub** [comment]
@heytherewill thanks for your feedback! Yes, let's make EBNF the final source of truth. I'll update the doc to include your comments there.

> Cookware quantity is valid (is this correct or a mistake? I think it should be valid)

Yes, I added example [here](https://github.com/cooklang/spec/issues/18)

> Timers can have names

Yep, for example in the app it's possible to set multiple timers, so name can come handy

> Ingredients, timers and equipment can only use the latin alphabet whereas comments, steps and metadata can use whatever (I think the spec for the special elements is too restraining. Even if we are not talking about non-latin alphabet languages, diacritics are not included as valid alphabetic characters)

Good point. I updated EBNF to use Unicode categories. This way it will be explicit and make more sense than only Latin alphabet in names.

**Comment by dubadub** [comment]
Added BNF and canonical tests, closing the issue.
