### ISSUE TITLE
Prep time and cook time

### ISSUE THREAD

**Issue by deathau** [cooklang/spec#29]
Some recipes in my experience differentiate cooking time from prep time, and I was wondering if there was some sort of way to incorporate that into the spec?

For example, we could use terms like `cook` and `prep` in the existing timer syntax:
```
Rest the dough for ~prep{10%minutes}
Bake for ~cook{15%minutes} or until golden brown.
```
You could also do something like specifying cook time with a specific syntax like this and any other timer counts as prep time.
Just some suggestions.

**Comment by dubadub** [comment]
I think it's a useful feature and it's actually supported by the parser. Although it was never mentioned in the spec. 

As you said, every timer can have a name and applications can use this name in different ways, for example tailor notification messages: "Your dough rest timer is done" or something like this.

I updated spec with this information https://github.com/cooklang/spec/commit/841dae94a4bccbd6c282791694a899cf680a631b.

**Comment by deathau** [comment]
That's cool. Thanks for updating it in the spec, too 👍
