### ISSUE TITLE
Dynamic servings

### ISSUE THREAD

**Issue by umgefahren** [cooklang/spec#3]
Add the feature for dynamically calculating the amount of ingredients needed depending on how many servings one wants to cook.
This _dynamic ingredient amount_ would also perfectly integrate with the shopping list.
This would allow cooking servings greater than the amount specified by the recipe. Hand in hand with that a specification for the interpretation for 1 serving is needed. 
The syntax could be like this:
```
>> servings: [1) // 1 to infinite amount
>> servings-interpretation: Amount of cupcakes one wants to cook.
Add @milk{1/2*%cup} and mix until smooth.
```

**Comment by dubadub** [comment]
@umgefahren I think this is a useful feature and it doesn't require any new syntax. From the servings we can understand the model of scaling and extrapolate or interpolate to the requested servings parameter from the arguments passed to parser.

**Comment by umgefahren** [comment]
I think you're right. You may close the issue, if you think this is resolved.
