### ISSUE TITLE
Guidance for combing ingredients

### ISSUE THREAD

**Issue by deathau** [cooklang/spec#35]
When parsing and then formatting a recipe, it's common to list the ingredients first. But if the same ingredient appears twice in the same recipie, is there any guidance on combining them in the ingredients list?
So, for example, if I have a recipe like:
```
Crack the @eggs{3} into a blender, then add the @flour{125%g}, @milk{250%ml} and @sea salt{1%pinch}, and blitz until smooth.

Separate @eggs{2} into separate bowls.
```
I get an ingredients list that looks like:
- 3 eggs
- 125 g flour
- 250 ml milk
- 1 pinch sea salt
- 2 eggs

I'd prefer to see something like:
- 5 eggs, divided
- 125 g flour
- 250 ml milk
- 1 pinch sea salt

but there are a few challenges involved in combining ingredients. First and foremost, units. It's easy to combine if there are no units or units are identical, but since units are just free text, there might have to be conversion, pluralisation, etc in order to get them to a point where they can be combined...  
I'm just wondering if there is any guidance about what _should_ be done, and if that's worth mentioning in the spec?

**Comment by dubadub** [comment]
There's no guidance as such, but I can share what approach I used in CookCLI and iOS app: combine combinable, and output amounts separated by comma.

Here's an example output from my shopping list:
```
FRUIT AND VEG
    beetroots                     300 g, 3 medium
    carrots                       300 g, 6 items, 1 large
    ...
    mushrooms                     300 g, 4 medium
    onions                        2 large, 4 medium, 1 small
    potatoes                      870 g, 6 medium, 8 small

```
In the same way it works for a single recipe. Note, that the structure is a bit different from yours.

We can do our best with combining part, and this will be improved later when we finalise approach to units conversions. But in any case it will be optional to setup conversion rules, hence we should expect multiple units. 

Final result will greatly depend on how much "messiness" the user wants to accept: for some it doesn't matter that units not consistent from recipe to recipe and some will have all recipes in a standard format.

I might create a page where list similar guidelines for application developers if you consider it useful.

**Comment by deathau** [comment]
I see, so for something like `@flour{3%cups}, @flour{125%g}, @flour{200%g}`
you would end up with something like `flour — 3 cups, 225 g`
(then in future with unit conversion and density information we can combine them even more)

I guess this is one of those situations where it's really up to the developer and the language doesn't really specify how it should be done? a shopping list consisting of
```
flour    3 cups
flour    125 g
flour    200 g
```
... is perfectly acceptable (though obviously not a great user experience).
(sorry, just getting my thoughts out there).

Thanks for the guidance. Some documentation with information along these lines would be useful, I guess. But it's not really part of the spec, either.
