### ISSUE TITLE
Cooklang Tree Sitter

### ISSUE THREAD

**Issue by addcninblue** [cooklang/spec#44]
Hi! I really enjoyed this language, but it didn't have a tree-sitter syntax written. As a result, I went ahead and began writing one over at https://github.com/addcninblue/tree-sitter-cooklang. I figured this is probably a good place to make this known. At the moment, parsing is nearly all correct, and highlighting is the only thing remaining to be done.

Let me know if you'd like this to be merged into a cooklang/ project, or if you'd like to keep this separate for now. Hopefully this is of use to some people!

Thanks!

**Comment by dubadub** [comment]
Wow! That's really great! Thanks @addcninblue! 

I listed your repo in spec https://github.com/cooklang/spec/commit/d0e6322386957f318b0b12f6c954e5de23b04d82. Please, give me some time to think about merging it into Cooklang organisation.

**Comment by addcninblue** [comment]
Thanks a lot! Yes, no worries, I'm fine with either!

**Comment by dubadub** [comment]
@addcninblue let's keep it under your account for now.

**Comment by addcninblue** [comment]
As an update to this, I added the tree-sitter parser into neovim, so users of neovim tree-sitter should have proper syntax highlighting for cooklang files:

https://github.com/nvim-treesitter/nvim-treesitter/commit/2dfe7a5839fe508f50929f33ab948d8485e3f5a9
