### ISSUE TITLE
[Syntax Highlighting] nano text editor

### ISSUE THREAD

**Issue by le-jun** [cooklang/spec#49]
Hey there, I made a [quick draft](https://github.com/le-jun/cooklang.nanorc) of cooklang spec syntax highlight for the nano text editor. Feel free to copy it under a cooklang repo!
It kinda works, the only issue being the ingredients and cookware requiring brackets even for one word items. I just couldn’t get my mind around regexp to make it work.

**Comment by dubadub** [comment]
@le-jun, thanks a lot! I listed your project in syntax highlighting section https://github.com/cooklang/spec/commit/9959ab29b2ddf5500dd5c3a51c784a55c2fc2cc1.
